print('Is JJ Lin handsome?')
print('Yes!')
print('Can you fight with a dragon?')
print('I can!')
print('Where are you from?')
print('I am from Mars!!!')
print('Is your younger brother crazy?')
print('Yes!Very crazy.')
print('Will your mother be dissappointed to see your math grades')
print('No!Because I am smart!')